### ISSUE TITLE
Reporte Seguimiento y Control 

### ISSUE THREAD

**Issue by IMA-G** [SistemasTecTlaxiaco/actividad-9-practica-de-seguimiento-y-control-de-proyecto-balam#1]
[Seguimiento y Control.pdf](https://github.com/SistemasTecTlaxiaco/actividad-9-practica-de-seguimiento-y-control-de-proyecto-balam/files/10188899/Seguimiento.y.Control.pdf)

**Comment by salathiel1999** [comment]
50%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
